<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PDFDocumentStudio.Core\PDFDocumentStudio.Core.csproj" />
    <ProjectReference Include="..\PDFDocumentStudio.Pdf\PDFDocumentStudio.Pdf.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
